# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- umd

pool:
  vmImage: ubuntu-latest

steps:
- script: yarn install --frozen-lockfile
  displayName: 'yarn install'

- script: yarn build
  displayName: 'yarn build'

- script: yarn build:umd
  displayName: 'yarn build:umd'

- script: yarn pack
  displayName: 'yarn pack'

- task: CopyFiles@2
  inputs:
      contents: '*.tgz'
      targetFolder: $(Build.ArtifactStagingDirectory)
  displayName: 'Copy archives to artifacts staging directory'

- task: PublishBuildArtifacts@1
  inputs:
      targetPath: $(Build.ArtifactStagingDirectory)
      artifactName: package
  displayName: 'Publish artifacts'
